FROM ubuntu:24.04

# Set environment variable for .NET globalization
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    apt-get install -y gdal-bin libgdal-dev && \
    rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --upgrade pip

WORKDIR /app

COPY . /app

# RUN pip install --no-cache-dir -r requirements.txt

# CMD ["python", "src/examples.py"]

# ...existing code...
CMD ["bash"]
