FROM python:3.11-slim

# Set environment variable for .NET globalization
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1

RUN apt-get update && \
    apt-get install -y gdal-bin libgdal-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . /app

# RUN pip install --no-cache-dir -r requirements.txt

# CMD ["python", "app/src/examples.py"]
