FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app
COPY . /app

RUN apt-get update && apt-get install -y \
    python3 python3-pip \
    gdal-bin libgdal-dev \
    libssl1.1 \
    && rm -rf /var/lib/apt/lists/*

RUN apt install python3-poetry

RUN poetry config virtualenvs.create false \
    && poetry install --no-dev

CMD ["python3", "src/examples.py"]
