FROM ubuntu:24.04

# Avoid interactive prompts
ENV DEBIAN_FRONTEND=noninteractive
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1

# Set working directory
WORKDIR /app

# Copy application files
COPY . /app

# Install prerequisites
RUN apt-get update && apt-get install -y \
    python3 python3-pip \
    wget \
    gdal-bin libgdal-dev \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Manually install libssl1.0 from Ubuntu 20.04
RUN wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.13_amd64.deb && \
    dpkg -i libssl1.0.0_1.0.2n-1ubuntu5.13_amd64.deb && \
    rm libssl1.0.0_1.0.2n-1ubuntu5.13_amd64.deb


# Install Poetry
ENV POETRY_VERSION=1.8.2 \
    POETRY_HOME="/opt/poetry" \
    PATH="/opt/poetry/bin:$PATH" \
    POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_CREATE=false

RUN curl -sSL https://install.python-poetry.org | python3 -

# Install Python dependencies via Poetry
RUN poetry install --no-root --no-interaction

# Default command
CMD ["poetry", "run", "python3", "src/examples.py"]
