FROM ubuntu:24.04

# Avoid interactive prompts
ENV DEBIAN_FRONTEND=noninteractive
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1

# Set working directory
WORKDIR /app

# Copy application files
COPY . /app

# Install prerequisites
RUN apt-get update && apt-get install -y \
    python3 python3-pip \
    wget \
    gdal-bin libgdal-dev \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Manually install libssl1.0 from Ubuntu 20.04
RUN wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.13_amd64.deb && \
    dpkg -i libssl1.0.0_1.0.2n-1ubuntu5.13_amd64.deb && \
    rm libssl1.0.0_1.0.2n-1ubuntu5.13_amd64.deb

# Install Python requirements
RUN pip install --no-cache-dir --break-system-packages -r requirements.txt

# Default command
CMD ["python3", "src/examples.py"]
