[tool.poetry]
name = "gdal-poc"
version = "0.1.0"
description = "this is point of concept for convert from wsg and gdb to geojson using Gdal library"
authors = ["yagel"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
gdal = "3.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "aspose"
url = "https://pypi.aspose.com/artifactory/api/pypi/aspose-python-api/simple"
priority = "explicit"
